CREATE TABLE IF NOT EXISTS "TICKER".income_statement (
    id SERIAL PRIMARY KEY,
    "Year" INT,
    "Quarter" INT,
    "Net interest income" NUMERIC,
    "Interest and similar income" NUMERIC,
    "Interest and similar expenses" NUMERIC,
    "Net fee and commission income" NUMERIC,
    "Fees and commission income" NUMERIC,
    "Fees and commission expenses" NUMERIC,
    "Net gain (loss) from trading of foreign currencies" NUMERIC,
    "Net gain from trading of held-for-trading securities" NUMERIC,
    "Net gain from trading of investment securities" NUMERIC,
    "Net other income/expenses" NUMERIC,
    "Other income" NUMERIC,
    "Other expenses" NUMERIC,
    "Income from investments in other entities" NUMERIC,
    "Operating expenses" NUMERIC,
    "Operating income before allowance for credit losses" NUMERIC,
    "Allowance expenses for credit losses" NUMERIC,
    "Profit before tax" NUMERIC,
    "Corporate income tax" NUMERIC,
    "Business income tax - current" NUMERIC,
    "Business income tax - deferred" NUMERIC,
    "Net Profit" NUMERIC,
    "Attributable to parent company" NUMERIC,
    "Minority interest" NUMERIC,
    "Sales" NUMERIC,
    "Sales deductions" NUMERIC,
    "Net sales" NUMERIC,
    "Cost of goods sold" NUMERIC,
    "Gross profit" NUMERIC,
    "Financial income" NUMERIC,
    "Financial expenses" NUMERIC,
    "Including: Interest expense" NUMERIC,
    "Selling expenses" NUMERIC,
    "General & administrative expenses" NUMERIC,
    "Operating income" NUMERIC,
    "Other income (expense)" NUMERIC,
    "Net profit" NUMERIC,
    "EPS" NUMERIC,
    "Outstanding Share" NUMERIC,
    "EBITDA" NUMERIC,
    "EBIT" NUMERIC
);