CREATE TABLE IF NOT EXISTS "TICKER".balance_sheet_quarterly (
    id SERIAL PRIMARY KEY,
    "Year" INT,
    "Quarter" INT,
    "Assets" NUMERIC,
    "Cash, gold and gemstones" NUMERIC,
    "Balances with the State Bank of Vietnam (SBV)" NUMERIC,
    "Deposits with and loans to other credit institutions (CIs)" NUMERIC,
    "Net trading securities" NUMERIC,
    "Trading securities" NUMERIC,
    "Provision for trading securities" NUMERIC,
    "Derivatives and other financial assets" NUMERIC,
    "Net loans to customers" NUMERIC,
    "Loans to customers" NUMERIC,
    "Provision for loans to customers" NUMERIC,
    "Investment securities" NUMERIC,
    "Available-for-sale securities" NUMERIC,
    "Held-to-maturity securities" NUMERIC,
    "Provision for investment securities" NUMERIC,
    "Long-term investments" NUMERIC,
    "Other long-term investments" NUMERIC,
    "Provision for long-term investments" NUMERIC,
    "Fixed assets" NUMERIC,
    "Tangible fixed assets" NUMERIC,
    "Intangible fixed assets" NUMERIC,
    "Investment properties" NUMERIC,
    "Other assets" NUMERIC,
    "Liabilities" NUMERIC,
    "Due to the Government and the SBV" NUMERIC,
    "Deposits and borrowings from other CIs" NUMERIC,
    "Deposits from customers" NUMERIC,
    "Derivatives and other financial liabilities" NUMERIC,
    "Other borrowed and entrusted funds" NUMERIC,
    "Valuable papers issued" NUMERIC,
    "Other liabilities" NUMERIC,
    "Shareholders' Equity" NUMERIC,
    "Share capital" NUMERIC,
    "Charter capital" NUMERIC,
    "Other capital" NUMERIC,
    "Reserves" NUMERIC,
    "Foreign exchange differences" NUMERIC,
    "Differences upon asset revaluation" NUMERIC,
    "Retained earnings" NUMERIC,
    "Minority interests" NUMERIC,
    "TOTAL ASSETS" NUMERIC,
    "CURRENT ASSETS" NUMERIC,
    "Short-term investments" NUMERIC,
    "Short-term receivables" NUMERIC,
    "Net inventories" NUMERIC,
    "Other current assets" NUMERIC,
    "LONG-TERM ASSETS" NUMERIC,
    "Long-term receivables" NUMERIC,
    "Long-term assets in progress" NUMERIC,
    "Other long-term assets" NUMERIC,
    "TOTAL RESOURCES" NUMERIC,
    "TOTAL LIABILITIES" NUMERIC,
    "Current liabilities" NUMERIC,
    "Short Term Debt" NUMERIC,
    "Long-term liabilities" NUMERIC,
    "Long Term Debt" NUMERIC,
    "OWNER'S EQUITY" NUMERIC,
    "Capital and reserves" NUMERIC,
    "Share Capital" NUMERIC,
    "Other Owners' Capital" NUMERIC,
    "Undistributed earnings" NUMERIC,
    "Budget sources and other funds" NUMERIC
);