name: Release

on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          pip install uv
          uv venv
          source .venv/bin/activate
          uv pip install python-semantic-release

      - name: Run semantic release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          source .venv/bin/activate
          semantic-release publish -vv
