name: semantic-release
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      actions: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Python Semantic Release
        id: semantic-release
        uses: python-semantic-release/python-semantic-release@v10.0.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          push: false

      - name: Create Pull Request
        if: ${{ steps.semantic-release.outputs.released == 'true' }}
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore(release): ${{ steps.semantic-release.outputs.version }}"
          title: "chore(release): ${{ steps.semantic-release.outputs.version }}"
          body: "Automated release PR"
          branch: "release/${{ steps.semantic-release.outputs.version }}"